media: assets
content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    view:
      fields: [ cover, title, published, date ]
    fields:
      - { name: image, label: Cover image, type: image }
      - { name: thumbnail, label: Thumbnail, type: image }
      - { name: body, label: Body, type: rich-text }