title: "5amu@blog:~$"
description: "Valerio Casalino's blog on offensive security, vulnerability management, and cybersecurity research."
markdown: kramdown
url: "https://5amu.github.io"
baseurl: ""

# for atom feed
author:
  name: Valerio Casalino
  email: casalinovalerio.cv [at] gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /p/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md", "CLAUDE.md", "Gemfile", "Gemfile.lock"]
