title: "5amu@blog:~$"
markdown: kramdown
url: ""
baseurl: ""

# for atom feed
author:
  name: Valerio Casalino
  email: casalinovalerio.cv [at] gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

placeholder: /assets/icons/placeholder.png

posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /p/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
